<a href="https://colab.research.google.com/github/Maxie503/CampusX-100Days-of-DL/blob/main/DAY63_LSTM_%7C_Part_3_%7C_Next_Word_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [2]:
import tensorflow as rf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [3]:
token = Tokenizer()

In [4]:
token.fit_on_texts([faqs])

In [5]:
token.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [6]:
len(token.word_index)

282

In [7]:
# Logic Test
coded= token.texts_to_sequences(['Discussion on Job hunting strategies \n Portfolio Building sessions'])[0]
coded

[279, 18, 280, 281, 282, 273, 274, 17]

In [8]:
# Logic Test
for i in range(1, len(coded)):
  print(coded[:i+1])

[279, 18]
[279, 18, 280]
[279, 18, 280, 281]
[279, 18, 280, 281, 282]
[279, 18, 280, 281, 282, 273]
[279, 18, 280, 281, 282, 273, 274]
[279, 18, 280, 281, 282, 273, 274, 17]


In [9]:
input_sequence = []
for sentences in faqs.split('\n'):
  tokenize_sentences = token.texts_to_sequences([sentences])[0]
  for i in range (1, len(tokenize_sentences)):
    input_sequence.append(tokenize_sentences[:i+1])


In [10]:
max_len = max([len(x) for x in input_sequence])

In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [12]:
paded_input=pad_sequences(input_sequence, maxlen=max_len, padding='pre')
paded_input

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]], dtype=int32)

In [13]:
X =paded_input[:,:-1]
y = paded_input[:,-1]

In [14]:
X

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]], dtype=int32)

In [15]:
print("X=",X.shape,"\ny=", y.shape)

X= (863, 56) 
y= (863,)


In [16]:
from tensorflow.keras.utils import to_categorical

In [17]:
y= to_categorical(y, num_classes=len(token.word_index)+1)

In [18]:
y.shape

(863, 283)

In [19]:
from tensorflow.keras.layers import Dense,LSTM,Embedding
from tensorflow.keras.models import Sequential

In [20]:
m1 = Sequential()
m1.add(Embedding(283,100, input_length=56))
m1.add(LSTM(150))
m1.add(Dense(283, activation='softmax'))
m1.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
m1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
m1.fit(X,y,epochs=100)


Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.0531 - loss: 5.5347
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0805 - loss: 5.0969
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0657 - loss: 5.0228
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0758 - loss: 4.9106
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0726 - loss: 4.9413
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0855 - loss: 4.8529
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1006 - loss: 4.6940
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1191 - loss: 4.5363
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1715 - loss: 4.2520
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2124 - loss: 4.0521
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2089 - loss: 3.8989
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy

In [32]:
text = "mail"

ytest = token.texts_to_sequences([text])[0]
ytest_pad=pad_sequences([ytest], maxlen=56, padding='pre')
ytest_pad

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0, 61]], dtype=int32)

In [35]:
m1.predict(ytest_pad).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


(1, 283)

In [37]:
import numpy as np

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


274

In [46]:
pos = np.argmax(m1.predict(ytest_pad))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


In [47]:
for key,value in token.word_index.items():
  if value == pos:
    print(key)

building


In [62]:
# Test

text = "NLP"


for i in range(10):
  ytest = token.texts_to_sequences([text])[0]
  ytest_pad=pad_sequences([ytest], maxlen=56, padding='pre')

  pos = np.argmax(m1.predict(ytest_pad))

  for word,value in token.word_index.items():
    if value == pos:
      text = text +" "+ word
      print(text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
NLP and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
NLP and deep
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
NLP and deep learning
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
NLP and deep learning and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
NLP and deep learning and nlp
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
NLP and deep learning and nlp be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
NLP and deep learning and nlp be a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
NLP and deep learning and nlp be a part
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
NLP and deep learning and nlp be a part of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
NLP and deep learning and nlp be a part of this
